import "reflect-metadata";
import "../../polyfills";

import type { Metadata } from "next";
import "./globals.css";
import { FooterComponent } from "@/core/components/footer/footer.component";
import { Navbar } from "@/core/components/navbar/navbar.component";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
